### ISSUE TITLE
Metrics breaking on 400 & 500 responses

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#1031]
**Describe the bug**
When the metrics api returns a 400/500/503 response the UI breaks.

**To Reproduce**
1. Go to https://8-d0dca6e3d1-fskzdv.manager.zesty.io/settings/metrics
4. See UI stays in loading state

**Expected behavior**
400 is being returned stating "ZUID: 8-c9bde4-0000 is not valid" (0000 added for id obfuscation) for instances which exist and are loading in manager-ui. The UI needs to display an error screen not an app crash when this occurs.

while the 500/503 needs to be solved at the API the UI should understand when it receives this failed response and display something past loading screen

**Screenshots**
![image](https://user-images.githubusercontent.com/208819/164761751-1b4fe42a-5fda-4961-87fa-f14fa700e9cb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MukeshGKastala** [comment]
**API**
The Metrics API endpoint `/usage` was erroneously returning a 500 for instances without a site media bin. The API, for the `/usage` endpoint, was updated to return a 404 when an instance doesn't have a site media bin. Note that an instance not having a site media bin is a bug on its own. 

The Metrics API was returning a 503 when requests to BigQuery were taking more than a ~1s due to a timeout race condition. The race condition was removed.

**UI**
Manager UI no longer hangs on the loading screen. It instead crashes.
![Screen Shot 2022-04-27 at 4 39 59 PM](https://user-images.githubusercontent.com/9838347/165642997-ab3662b8-7d67-44c6-89b0-3a58ef7954e6.png)
