### ISSUE TITLE
Settings / Metrics 

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/manager-ui#1040]
**Describe the bug**
Crashing when selecting Past Day

![Screen Shot 2022-05-04 at 2 30 20 PM](https://user-images.githubusercontent.com/22800749/166829031-6d43a190-1980-437c-af84-24ae22d76b60.png)

https://www.screencast.com/t/hlEeoCTqZRkk

**Comment by rjpals** [comment]
What branch & environment are you running this on? I can reproduce on prod, but my local dev environment running `master` works just fine.

I believe this issue is caused by the fact that there were no `403` response codes served during the selected time period. It *should* be fixed by [this commit](https://github.com/zesty-io/manager-ui/pull/1032/commits/9729b6d8e63c7cfc3845a93c1dd7afa3d7c7a1c5). It appears to me that that commit is not on prod currently.

**Comment by d88naimi** [comment]
Okay thank  you I will close this ticket out since you have a PR up for it.
CC: @shrunyan
