### ISSUE TITLE
Media App: Use "_" instead of "-" for files which have a space in their file name

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#1448]
**Problem:** 
When I upload a file which has spaces in it's file name such as "drone 123.png" the back end changes the file name to "drone-123.png". 
"-" are difficult to read and make the file name read as one giant word. 

**Solution**
Hence can we use "_" instead of "-". For example "Food 123" should be "Food_123" instead of "Food.123"

**Comment by mattezra** [comment]
@zcolah This is not a change we will do due to the SEO impact based on Google's recommended [URL structure](https://developers.google.com/search/docs/crawling-indexing/url-structure) :
> Consider using hyphens to separate words in your URLs, as it helps users and search engines identify concepts in the URL more easily. We recommend that you use hyphens (-) instead of underscores (_) in your URLs.

More resources here:
https://www.mtu.edu/umc/services/websites/writing/characters-avoid/
https://superuser.com/questions/1437946/in-the-quest-for-the-perfect-file-naming-scheme-spaces-dash-and-underscores

I am going to close this ticket. Feel free to reopen this if you want to continue the conversation.
