### ISSUE TITLE
The Model Parent value is not displayed in the "Update Model Parent" schema settings

### ISSUE THREAD

**Issue by b-estevez** [zesty-io/manager-ui#1935]
Instance Zuid:  8-ac91ad86e9-txcblw

As we can see in the image below, all headless models are all under of "Homepage" single page model:
![image](https://user-images.githubusercontent.com/55866499/225970107-45f3ae4b-5cde-4cb2-9e97-d31cf7165cdc.png)

also looking from the api, those headless models have a parentZUID value: "7-c8fbcdd3a1-wrn5jp"which is the item zuid of the **Homepage**
![image](https://user-images.githubusercontent.com/55866499/225971001-9429e487-0343-44ad-b569-31e1eaab87b0.png)
<br>
![image](https://user-images.githubusercontent.com/55866499/225971118-882cda58-9299-4692-95f4-1a608f973577.png)
<br>
![image](https://user-images.githubusercontent.com/55866499/225971521-4b958d36-6990-4ef5-9618-c5ebe224c059.png)

But in the schema settings under **Info,** those headless models have no parent model (sample image below):

![image](https://user-images.githubusercontent.com/55866499/225971996-7e50ee73-46dd-4d75-b6b6-2718d180e988.png)

![image](https://user-images.githubusercontent.com/55866499/225972082-598efb44-d043-40f8-a7e6-a2242c977c3e.png)

Because of this, the user cannot update the parent model of a specific model.

Please feel free to reach out for more details in regards to this.

**Comment by b-estevez** [comment]
@agalin920 , those 3 headless models `hero_section`, `main_content`,`side_content` was already have a parent model which is "Homepage" before the new schema interface was released. Meaning I assigned the parent model with the old schema interface.

I was trying to remove the current parent model of each headless model but the current value of the parent model is "None". I also tried to save it with "none" as a parent model value but those 3 headless models are still under "Homepage" content item.
![image](https://user-images.githubusercontent.com/55866499/226319824-ef4b1280-483f-4d11-be06-75b38ed3a4f3.png)

**Comment by giseleblair** [comment]
@agalin920 according to the API we should be allowed to select a 7- item (so long as that's a single page model) https://www.loom.com/share/bbd3d2241b0c417baccaa5a96cd65032

**Comment by giseleblair** [comment]
@agalin920  yes, that sounds like a good approach

**Comment by theofficialnar** [comment]
@agalin920 gotcha, I'll change the dropdown options for parent zuid to the values from `/env/nav`.

**Comment by theofficialnar** [comment]
Hey @giseleblair, just wanted to confirm something as I have stumbled on this while testing out the fix. I noticed that updating the parent model of an already existing single page model doesn't change where it is nested in the content nav, it just stays on where it was originally on the content nav, it doesn't matter what the selected parent model's type is. I had to manually change that single page item's path under seo & meta for it to be nested correctly on the content nav. It's also worth noting that I'm already using the correct parentZUIDs from `/env/nav` - since this is the fix for the original issue raised by @b-estevez. For headless and multi-page models there are no issues.  I tried on both new and old schema and it behaves the same way for single page models.

https://user-images.githubusercontent.com/28705606/227855896-6a1fd16c-e8fc-48ba-949f-090dda85b980.mp4

**Comment by giseleblair** [comment]
@theofficialnar 
Changing a parent model of existing item(s) does not retroactively change the parent of that item. Setting a parent model will only take effect when new a new item is created after the parent has been declared. This may be a warning we should setup when changing the parent of a model with existing items. Can you also test this workflow with data set model types: multi-page and headless. What does the navigation behavior look like for both of these models?

**Comment by giseleblair** [comment]
@theofficialnar please also test with multi-lang enabled

**Comment by theofficialnar** [comment]
> @theofficialnar Changing a parent model of existing item(s) does not retroactively change the parent of that item. Setting a parent model will only take effect when new a new item is created after the parent has been declared. This may be a warning we should setup when changing the parent of a model with existing items. Can you also test this workflow with data set model types: multi-page and headless. What does the navigation behavior look like for both of these models?

@giseleblair  Here's what happens to the item's location in the content nav tree on both old and new schema after the model's parent has been changed.

Old Schema:
Single page - not moved in content app nav tree when creating a new item after model parent was changed
Multi - moved immediately after model parent was changed
Headless - moved immediately after model parent was changed

New Schema
Single page - not moved in content app nav tree when creating a new item after model parent was changed
Multi - moved immediately after model parent was changed
Headless - moved immediately after model parent was changed

So it seems like Single Page items really just stay where they are on the content app's nav tree even after changing its model's parent schema since it behaves the same way on both old and new schema.
