### ISSUE TITLE
Content: Bynder Integration

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2157]
# Intro 
Allow a user to add images and files into their Content Item from Bynder instead of the Zesty Digital Asset Manager. 

# User Setup
![image](https://github.com/zesty-io/manager-ui/assets/22625919/00b2c6a8-97fc-4116-acc6-6ea74c94d273)

# Upload from Bynder
![image](https://github.com/zesty-io/manager-ui/assets/22625919/3d1a7ce8-19be-489a-8f3d-736031df24e1)

# Bynder Asset Preview
![image](https://github.com/zesty-io/manager-ui/assets/22625919/2c9fe286-8a1c-4808-b9f9-fd447fce968e)

# Bynder WYSIWYG Button
![image](https://github.com/zesty-io/manager-ui/assets/22625919/dd3ee920-207b-4880-a70f-35f8f22f6559)

# For Developers
Please look at the comments on this Figma file (https://www.figma.com/file/XPjxuxpmkvnMHhzAFXLZBW/Bynder-Integration?type=design&node-id=0%3A1&mode=dev&t=Nt8qm7dk9W4obYth-1) and investigate the bynder integration possibilities. 

## Docs

1. https://developer-docs.bynder.com/ui-components

2. https://support.bynder.com/hc/en-us/articles/360014369640-Universal-Compact-View-Overview-Page
3. https://bynder.docs.apiary.io/#introduction/welcome-to-the-bynder-api-documentation

**Comment by theofficialnar** [comment]
API docs: https://bynder.docs.apiary.io/#introduction/welcome-to-the-bynder-api-documentation

**Comment by theofficialnar** [comment]
Todo
- [x] Add Bynder to settings app
- [x] Bynder authentication flow in settings app
- [ ] Support Bynder assets in media field
  - [ ] Initial selection of files and rendering
  - [ ] Add more files
  - [ ] Wire remove bynder files
  - [ ] Wire replace bynder files
- [ ] Support adding Bynder files in wysiwyg
  - [ ] Add bynder files button in toolbar
  - [ ] Render bynder assets in wysiwyg

**Comment by theofficialnar** [comment]
@zcolah currently in the media field we can only store Zesty media ZUIDs and/or direct asset urls. Due to this there are 2 ways of how we can save the Bynder assets, one being a quick and easy way to do it and the other requires more things to be setup with potential drawbacks.

**Save the Bynder asset's original url (the url pointing to the file)**
  - Pros:
    - Easier to implement as we only need to rely on Bynder's UCV and we're just saving the direct file urls whenever a user selects a Bynder asset
    - No need to do any other api calls to Bynder to retrieve any data
    - Webengine can support the file out of the box since this is just a plain file url
  - Cons:
    - Will not have detailed asset data since we only have the file url, therefore we cannot show the file name, description and we won't also be able to let users click on the asset on the media field preview to redirect them to the Bynder portal preview to rename the file etc.
 
or

**Save the Bynder asset's ID**
- Pros:
  - Basically resolves the Cons on the first option, we could show more detailed info about the Bynder asset including allowing click to redirect to the Bynder asset portal preview
- Cons:
  - Needs the users to configure their Bynder portals to allow third-party apps from having access to their files
  - Would take more time to implement as we need to setup a dedicated OAuth flow to allow us to make api calls to Bynder's api to fetch the data needed to render stuff like filenames, file url etc.
  - I'm assuming this could possibly break the UI if the user is currently not authenticated with Bynder and they're trying to preview a Bynder asset that's on media field. Since if the api call fails, we won't have the asset preview, file name etc. to show on the media field preview
  - Probably needs some changes on webengine so that it knows how to generate the file's direct url when given a Bynder asset ID.

**Comment by theofficialnar** [comment]
As discussed placing this to block to figure out whether or not we'd want to make a dedicated field type for bynder or not in order to retain bynder asset meta data

**Comment by theofficialnar** [comment]
Will be proceeding to storing the bynder asset direct url in the media field
