### ISSUE TITLE
New subfolders are not displaying in Media sidebar

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#2177]
When a new subfolder is added from the Media  app, it does not display in the left media sidebar. It will display in the main Media body when clicked into a folder, but it will not display in the sidebar.

Please view this customer's video for additional context: https://zestyiodevs.slack.com/archives/G9F6JTJ0Y/p1689359465700619?thread_ts=1689349615.663209&cid=G9F6JTJ0Y

**Comment by theofficialnar** [comment]
@giseleblair can't seem to view the video as I'm not a part of that slack group. I can't seem to replicate the issue, tried creating sub-folders on dev, stage and prod and they're all successful even on old and newly created instances. Also tried on both chrome and firefox.

**Comment by theofficialnar** [comment]
@giseleblair I tried checking this out and it seems like the order of the response from `/bin/[XXXXX]/groups` seems to be random. I'm assuming this used to return the bins in order of creation (correct me if I'm wrong @agalin920). Because when I tried creating a new folder it added that newly created folder in between some other already existing folders which causes the newly-created folder to not show up on top of the folder list even if the user has set the sorting to "Last Created". On the bright side, it will still add the newly-created folder on the sidebar, just not on top of the list like what the user expects.

@mattezra has the order of the responses from `/bin/[XXXXX]/groups` been changed?

**Comment by theofficialnar** [comment]
I'm not even sure if it's sorted by name since the newly created folders I made were made up of numbers and they have been placed in the middle of the api response.

**Comment by mattezra** [comment]
@theofficialnar no changes made on the media-manager-service ([api reference](https://media-api.zesty.org/#e9bc7028-d063-b48b-fa44-a50daaf4a70e)). Latest deploy of this was June 2022 as seen in [App Engine](https://console.cloud.google.com/appengine/versions?authuser=1&project=zesty-prod&serviceId=media-manager-service).

**Comment by theofficialnar** [comment]
> @theofficialnar no changes made on the media-manager-service ([api reference](https://media-api.zesty.org/#e9bc7028-d063-b48b-fa44-a50daaf4a70e)). Latest deploy of this was June 2022 as seen in [App Engine](https://console.cloud.google.com/appengine/versions?authuser=1&project=zesty-prod&serviceId=media-manager-service).

Hmm that's odd. I wonder what we can do about the last created sorting then since we can't seem to do it client-side due to the response not having any dates.

**Comment by mattezra** [comment]
> > @theofficialnar no changes made on the media-manager-service ([api reference](https://media-api.zesty.org/#e9bc7028-d063-b48b-fa44-a50daaf4a70e)). Latest deploy of this was June 2022 as seen in [App Engine](https://console.cloud.google.com/appengine/versions?authuser=1&project=zesty-prod&serviceId=media-manager-service).
> 
> Hmm that's odd. I wonder what we can do about the last created sorting then since we can't seem to do it client-side due to the response not having any dates.

Tagging @shrunyan this will be an enhancement in [media-manager-service](https://github.com/zesty-io/media-manager-service) for `/bin/[XXXXX]/groups` as right now, the database query for bin groups do not have sorting/ordering. The query right now is `SELECT * FROM groups WHERE bin_id = ?`.
