### ISSUE TITLE
Global search returns schema items to user with "Publisher" access

### ISSUE THREAD

**Issue by b-estevez** [zesty-io/manager-ui#2218]
A user with a Publisher role will see schema records returned in their search but the Publisher role does not have permission to view Schema records

**Comment by shrunyan** [comment]
An argument for having the permissions enforcement at the sub-app level is that awareness of an entity is typically not the concern but the read, write and delete permissions. With this in mind it is probably a better experience for a user who doesn't have those permission to see the entity in results as otherwise it could create confusion if a user is asked to work on a particular entity but it doesn't show up in results. As this could lead them to believe it doesn't exist. Versus that they don't have permission to work with it.

**Comment by zcolah** [comment]
I align with what @shrunyan has shared here

**Comment by theofficialnar** [comment]
If that's the case, is it safe to assume that this issue can be closed as we're leaning towards just leaving the result there and just let the sub-app handle permission access?

**Comment by zcolah** [comment]
Correct. Closing the issue now.
