### ISSUE TITLE
In-App Announcement: Time Zone Logic is not working as expected

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2370]
**Problem**
Currently when an In App Announcement goes out it displays based off the user's laptop's time zone. This means that the In App announcement only appears starting 8 AM in New York and 8 AM in Los Angeles. This means that the person in Los Angeles sees the In App announcement 3 hours later than the person in New York. This is not the experience we desire. 

**Solution** 
Please assume the timezone for the date time value from the API is in UTC Time Zone when checking to see if an in app announcement should be displayed. This will ensure that the In-App announcement Pop Up is available to everybody at the same time regardless of what time zone they are in. 

The experience we desire is that the In App announcement should appear at the same time irrespective of the time zone the user is in. This means that the In App Announcent Pop Up should appear at the same time irrespective of whether I am in Los Angeles or New York. If the Article is to go out at 8 AM New York, it means it should appear at 5 AM Los Angeles.

**Comment by theofficialnar** [comment]
Should this UTC+0?

**Comment by theofficialnar** [comment]
- [ ] Verify if datetime field is saving data to UTC+0

**Comment by theofficialnar** [comment]
@shrunyan after investigating this issue, it turns out that there are no UTC+0 conversions happening on the date and time fields when creating/editing content items. Whatever the user has selected is getting saved directly to the backend as is.


User input
![Image](https://github.com/zesty-io/manager-ui/assets/28705606/b81d7ca0-f95a-4bbd-9c23-4cf3846395bd)

Payload
![Image](https://github.com/zesty-io/manager-ui/assets/28705606/32cb5afa-bf4c-41f1-bfca-3b43da6cf6bc)

I could go ahead and add the utc+0 conversion before doing the api call to create/update the content items. But my concern is that it may cause some confusion since I would then need to convert all the date time values from the api to browser local time which will also affect all other date time values that have already been saved before.

**Comment by theofficialnar** [comment]
@agalin920 Yeah, that's what I thought so as well. I could then just update the in-app announcement component to make sure that it's using UTC+0 when checking if an announcement's start_date_time and end_date_time is in a valid range.

**Comment by shrunyan** [comment]
@theofficialnar in that case I think we will have to design and treat that field as a UTC+0 value. This way you can have a understood timezone reference for conversion. It will require the author to pick whatever time they want in their timezone and convert to UTC+0. e.g. If I am an author in the PST timezone and I want the announcement to go live at 8:00am PST then I need to enter 12AM. As PST is UTC+8.

**Comment by theofficialnar** [comment]
@shrunyan got it

@zcolah maybe it's also worth adding a description to the start_date_time and end_date_time fields in the in-app announcement's schema stating to place in UTC+0 date and times to remind everyone when making an in-app announcement content item.
