### ISSUE TITLE
Content: Boolean Field Revamp

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2451]
# Intro
The Boolean field will now use radio buttons instead of a toggle switch. This is because toggle switches cannot accomadate long values. 

![image](https://github.com/zesty-io/manager-ui/assets/22625919/3cc19c05-2188-47f3-9274-0c369a880621)

# Figma
https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=3598%3A141969&mode=dev&t=pEhzoZQ9MJreprAx-1

**Comment by giseleblair** [comment]
Brining over this ticket that also has some notes on this field https://github.com/zesty-io/manager-ui/issues/2141

This field being called a "boolean" is misleading to the user. A boolean can have one of two values: true or false (which are not strings)
Our API allows for a `yes_no` field to hold any value. The manager interface does not allow for the user to edit these values and forces the interface user to use the values of `0` and `1` which is also misleading because while these are presented as integers, they are being output as strings. 

## Example of default interface values:
![Screenshot 2024-02-05 at 10 21 46 AM](https://github.com/zesty-io/manager-ui/assets/9896546/31cfc6b6-13ae-4b70-b0a3-5652ed53fd54)
 
## Example of API generated values
![Screenshot 2024-02-05 at 10 22 58 AM](https://github.com/zesty-io/manager-ui/assets/9896546/a82a22fc-93a8-43af-9265-c88a4304d3fb)

With the field being called "Boolean" the developer would expect that they can create boolean logic to display their data, which is not the case. Furthermore, as in the above linked ticket, there is a 3rd value of `null` which can also be passed which further complicates the developer's logic. 

Overall, this field needs some additional clarity by renaming it more appropriately, allowing the user to set their desired values in the interface per the API's documentation, and allow the user to set a default or fall back value if they don't want `null` to be an option.

**Comment by zcolah** [comment]
@giseleblair these are valid concerns which I have raised but unfortunately we do not have the backend budget to address them at the moment. I will keep this as a separate ticket for now on the backlog therefore.

**Comment by giseleblair** [comment]
I am going to elevate this on our support board, as this has been brought up by a couple of customers now

**Comment by giseleblair** [comment]
And as a follow up, if this is currently not in our radar for upcoming updates, should this be removed from the roadmap board?

**Comment by zcolah** [comment]
All ideas + feedback (new and old) go into the backlog of the product roadmap. Only when we start to pursue them, do they go into the "Development Queue". Therefore it can remain in our roadmap backlog. 


Also @giseleblair the ideal solution for this problem that was decided was to make the existing Boolean field as Legacy (similar to the legacy WYSIWYG). And to then make a new Boolean field that solves the problems above and that follows the best practices and expectations of developers and marketers. 

However we don't have any budget for it at the moment :/

**Comment by zcolah** [comment]
Just finished my conversation on this ticket with @giseleblair. It's clear that the proposed design solution does not solve for current customer problems. Hence I am closing this ticket as this solution is not appropriate. I am creating a separate ticket that describes each of the customer problems with the current interface along with a list of potential solutions. Will add a link to that ticket here once ready.
