### ISSUE TITLE
Activity Log: Actions such as Created Field and Created Model are not appearing for models

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2476]
See Loom: https://www.loom.com/share/ac6c85dde2204d84b936e306cfbe7c3b

Zesty Marketing Instance Model (where it does not work): 
https://8-da92b5d8e6-hvp4w4.manager.zesty.io/reports/activity-log/resources/6-f4ec9aa998-llpd07?from=2024-01-09&to=2024-01-26

Zesty Marketing Instance Model (where it works): 
https://8-aaeffee09b-7w6v22.manager.zesty.io/schema/6-45a908-qfw88c/activity-log?from=2015-03-03&to=2022-03-25

**Comment by theofficialnar** [comment]
@zcolah I am unable to replicate this since creating a new field on the same exact schema you mentioned above did log an entry.
![Image](https://github.com/zesty-io/manager-ui/assets/28705606/5d9566ae-5d81-4b4d-bf1d-ccacaf7e91f9)

 I am thinking this might be related to the question posted on the other bug ticket (https://github.com/zesty-io/manager-ui/issues/2477#issuecomment-2008578408) and worth waiting for @markelmad's response as well.

**Comment by zcolah** [comment]
sure sounds good, thank you for this update @theofficialnar

**Comment by markelmad** [comment]
@finnar-bin Same observation with this [issue](https://github.com/zesty-io/manager-ui/issues/2477#issuecomment-2008578408). See my [reply](https://github.com/zesty-io/manager-ui/issues/2477#issuecomment-2060092917).
