### ISSUE TITLE
Create new item page always makes a new draft after creating an item

### ISSUE THREAD

**Issue by agalin920** [zesty-io/manager-ui#2726]
1. Go to content item creation page
3. Save the item
4. Go to the multi item table
5. Observe a new draft item was created even tho one was just created

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by finnar-bin** [comment]
Seems like the issue happens when after creating a new content item and before the user gets redirected to the new content item `dispatch(generateItem(modelZUID))` is being triggered again. I've noticed that prior to the redirection, the fields get cleared out while still on the create item page which causes the generateItem function to be triggered.
