### ISSUE TITLE
Content: Multi Page table is not reflecting the order of the columns correctly

### ISSUE THREAD

**Issue by zcolah** [zesty-io/manager-ui#2824]
# Problem 

![Image](https://github.com/user-attachments/assets/0ef3c73f-b30d-4bb2-980b-ce181763880d)

![Image](https://github.com/user-attachments/assets/bfc841df-adda-492f-bfa9-3dee755df9be)

# Solution
The order of the columns should match the order of the fields in Schema

**Comment by finnar-bin** [comment]
@zcolah can you check if the "color" column is not pinned? Pinned items to the left will always show up first regardless of the defined field sorting in the model.

**Comment by zcolah** [comment]
@finnar-bin does our system remember the pinning?

**Comment by zcolah** [comment]
@finnar-bin I've made a Loom video with two examples. 
https://www.loom.com/share/a716499f44f84f318ce0bb7ee98ade1c?from_recorder=1&focus_title=1 

@giseleblair believes this may be because we are looking at the create date and time for the field potentially.

**Comment by finnar-bin** [comment]
@zcolah so what happens is that the very first time the multipage table is loaded, it will store the checkbox, version and whatever the first field at that point in time as the left pinned items, this setting will be saved in the local storage. So, what happens is that if you changed the sorting order in schema afterwards, that first field earlier will stay as pinned making it appear as the first column even if you've already changed the sorting in schema. Unpinning that column will properly put it in its proper place.

**Comment by finnar-bin** [comment]
@zcolah let me know if you want anything changed in how the pinning works here. Andres mentioned that it was a specific feature request to have the first field pinned.

**Comment by zcolah** [comment]
@finnar-bin 
Thank you for providing me with this context. Is it possible for us to: 

- Not store the pinned column setting in storage and instead load the first field of the model as pinned always
- Or is it possible for us if the pinned column is the same as the first field in the model? And if not, set the pinned column to be the first field? 

If yes, then please implement that.

**Comment by finnar-bin** [comment]
@zcolah I'll look into these suggestions once I wrap up the advanced sorting tickets

**Comment by finnar-bin** [comment]
> Not store the pinned column setting in storage and instead load the first field of the model as pinned always

This can be done and is probably the easiest to implement since they could just pin whatever column they need at that time. But this would mean that moving to a different page then going back to the table would reset the previously pinned columns.

> Or is it possible for us if the pinned column is the same as the first field in the model? And if not, set the pinned column to be the first field?

This can also be done but with a bit more complexity since we'd have to check whatever the previously pinned columns that are saved in the local storage with what the current model's field sorting is every time the table is loaded, then update the pinned columns every time that changes and save the changes to the local storage as well. Also, are we aiming to update the pinned columns **every time** the model's field sorting has been changed? I think that's going to be confusing since if someone has specifically pinned 2 columns for example, they'd probably expect that those columns they pinned always stay as pinned even if the model's field sorting has been updated.

**Comment by zcolah** [comment]
Hi @finnar-bin 
Thank you for bringing up these valid concerns. Let us move forward with solution 1. I am aware that this means the user will need to pin columns each time they leave the page but that is fair for now.
