### ISSUE TITLE
API > Site Generators page has extra 'null' keywords on the endpoints

### ISSUE THREAD

**Issue by Sammieboy00** [zesty-io/manager-ui#2898]
When going the the Site Generators Page for content items, there is an extra 'null' keyword on the available endpoints.

1. Go to any content item
3. Click on APIs tab
4. Click View Endpoints button on Site Generators option/block
5. Endpoints have the extra 'null' keyword. See attached screenshot

**Expected behavior**
The extra 'null' keywords should not be visible

**Screenshots**
![image](https://github.com/user-attachments/assets/6c291617-5226-4a58-8d9e-b3c56be77d2d)

**Comment by finnar-bin** [comment]
Seems to be happening to dataset items. These items do not have paths hence this issue happens since datasets aren't meant to have site generator urls.

@zcolah do you want the urls for datasets to always default to `/?toJSON` (therefore it's always referencing the homepage) here or should we just totally remove the site generators card from a content item's /api?

![image](https://github.com/user-attachments/assets/07cba3cb-5fb9-4e67-8371-41c1b4e8215a)

**Comment by zcolah** [comment]
@finnar-bin Please hide the Site Generators card for Dataset Models in Schema and Dataset Items in Content. This has been approved by @ardeay.
