### ISSUE TITLE
Cannot create/add new dataset item error

### ISSUE THREAD

**Issue by gtllien** [zesty-io/manager-ui#2984]
**Describe the bug**
User cannot create/add a new item in a dataset, there's a console error: `Cannot read properties of undefined (reading 'indexOf')`

**To Reproduce**
1. Go to a dataset content item
2. Click on '**Create**' or '**Create & Add New**'
3. Check browser's console error: _`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')`_

**Expected behavior**
User should be able to create or add new item in a dataset without any issues

**Screenshots**
![image](https://github.com/user-attachments/assets/602f7fb6-3b4e-49f5-be66-ccb2367f986c)

**Additional context**
Customer reported [issue](https://zestyiodevs.slack.com/archives/C029891CYJ3/p1727404877477849)

**Comment by zcolah** [comment]
@finnar-bin @agalin920 

- This has crept in due to the recent release. 
- Meta Title and Meta description should be: 
  - mandatory fields only for single page and multi page items 
  - optional for dataset items. 

Note: Remember to remove the asterisks from the labels of Meta title and Meta description when making them optional for dataset items.
