### ISSUE TITLE
Content: Locked Item Notice

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#326]
**Describe the bug**
The locked item modal notice needs styling. The spacing between paragraphs is missing and the modal footer actions should be split.

**To Reproduce**
1. Login with account A
2. Login with account B
3. Visit same url on both accounts
4. See locked item notice

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/208819/97391309-2e8eb000-189c-11eb-907f-2d351f737b75.png)

**Comment by shrunyan** [comment]
@d88naimi what is the status of this issue?

**Comment by shrunyan** [comment]
@d88naimi bumping issue

**Comment by d88naimi** [comment]
@shrunyan 
My styling is ready and can be merged to master however we worked on this ticket together a few months back and concluded something was off on with the knock if i'm not mistaken. You would let me know when it was resolved and then I can push up. I am not sure if the knock issue ever got resolved because I can't get the Item Locked modal to render.
