### ISSUE TITLE
IDE utility drawer close button scrolls with drawer

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#443]
**Describe the bug**
on smaller screens or in smaller browser windows the IDE utility drawer needs to scroll. However, when it scrolls the close button scrolls with the drawer and seems to 'disappear'. 

**To Reproduce**
1. Navigate to the Web IDE
2. Select a file (a view, a stylesheet, or javascript file)
3. Click on the button on drawer at the bottom of the code editor window to open it
4. if needed - resize your window to make drawer scroll - when you scroll the drawer the button will scroll with it. 

**Expected behavior**
The close button should be sticky and always show at the top of the drawer.

**Screenshots**
<img width="1125" alt="Screen Shot 2020-12-17 at 10 57 54 AM" src="https://user-images.githubusercontent.com/16694502/102533078-c5d0e200-4059-11eb-87b9-e08ea1c1850c.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 87

**Additional context**

**Comment by d88naimi** [comment]
@kakoga @shrunyan 

I can see where this would be a nice feature, Ive compared the functionality to legacy and it seems to be the same, not sure if this is a bug? 

The file drawer is a component being shared with media-manager now. I have tried a few options in making the handle drawer sticky as requested however since content varies in height this would need to be refactored in design-systems. This seems to be an issue with smaller viewports windows which is a smaller use case, @shrunyan please let me know if we want continue trying to implement this feature or waive? 

Notes*
Possible solutions would be to refactor the DrawerHandle to be position absolute to DrawerContent instead of siblings in design-systems.

**Comment by shrunyan** [comment]
@kakoga is noting this as a bug not a feature. @d88naimi are we recognizing the behavior @kakoga described as unintended or undesirable (a.k.a bug)?

**Comment by d88naimi** [comment]
@shrunyan i'm recognizing this as undesirable and the scroll bar renders for screens under 800px height .
