### ISSUE TITLE
Web IDE reordering does not immediately save new order

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/manager-ui#518]
**Describe the bug**
When using the drag & drop reorder module for schema or for WebIDE files, "dropping" the "dragged" item doesn't immediately save the new order. 

**To Reproduce**
1. Go to WebIDE and click "Order" button on style or js files.
2. Drag and drop an item to reorder
4. See the item will not reorder

**Expected behavior**
Expect the item to reorder on drag/drop

**Screenshots**
https://www.loom.com/share/dab12623591f44678f9907b7ef7b9a05

**Additional context**
The same experience is seen throughout the drag/drop reorder module. ie: reordering fields in schema

**Comment by shrunyan** [comment]
To clarify; "saving" the reorder happens when pressing the save button. This error is when you drag and drop the javascript files to reorder them it can re-render and revert to the prior order (state). It feels like an issue between redux state and react re-rendering. The odd part is if you re-order the javascript files again they will then stay as ordered.

**Comment by agalin920** [comment]
@giseleblair I believe the issue stuart mentioned above ("The odd part is if you re-order the javascript files again they will then stay as ordered.") got fixed with one of my feature requests https://github.com/zesty-io/manager-ui/issues/979.

Could you confirm so we can close this ticket please

**Comment by giseleblair** [comment]
@agalin920 the issue in #979 is a separate flow, but I just tested both and they seem to be resolved. Thank you for following up!
