### ISSUE TITLE
Clarifying Dashboard Top Buttons

### ISSUE THREAD

**Issue by chloespilotro** [zesty-io/manager-ui#557]
**Is your feature request related to a problem? Please describe.**
At the top of the new dashboard, there are 4 new buttons (Code, Schema, Audit Trail, Settings). These, to me, seemed like documentation hotlinks. I didn't realize these were links to each tab. 

**Describe the solution you'd like**
Not sure I have a suggestion to fix, just what I thought before clicking around.

**Describe alternatives you've considered**
Some other approach to styling maybe? 

**Additional context**
https://zesty-io.slack.com/files/U0B6LU3HS/F01QWB17E84/image.png

**Comment by d88naimi** [comment]
1) We could refactor that section to look like a traditional Nav bar 
![Screen Shot 2022-01-04 at 9 32 52 AM](https://user-images.githubusercontent.com/22800749/148099902-7b35d49e-8378-4bde-bfa5-77f74bcbf0ff.png)

2) I could add "Visit" in front of each nav link
3) We could move the links altogether since we already have the main side bar nav and move the documentation links to the bottom of the Dashboard (* My preference)
4) leave as is 

CC : @shrunyan

**Comment by shrunyan** [comment]
these are no longer present
