### ISSUE TITLE
Disable analytics button for non-admin/owner roles

### ISSUE THREAD

**Issue by kakoga** [zesty-io/manager-ui#638]
**Is your feature request related to a problem? Please describe.**
anyone can access the analytics section. This can create issues for users who inadvertently activate GA and create issues like duplicate events in GA

**Describe the solution you'd like**
hide the 'activate analytics' button from non-admin/owner users

OR

Make the analytics section inaccessible to non-owners/admins users

<img width="1362" alt="Screen Shot 2021-04-06 at 4 37 42 PM" src="https://user-images.githubusercontent.com/16694502/113791221-097a5500-96f8-11eb-8459-534a9077567e.png">

<br><br><i>(related to <a href='https://zestysupport.zendesk.com/agent/tickets/1826'>Zendesk ticket #1826</a>)<br>gz#1826</i>

**Comment by kakoga** [comment]
another idea from customer: which user clicks the button in Audit Trail

**Comment by shrunyan** [comment]
We should wrap the display of this button with the `usePermission` hook and only allow roles with the 'PUBLISH' action to see it

**Comment by kakoga** [comment]
could we lock it to the the same users that have launch permissions?

**Comment by shrunyan** [comment]
@d88naimi since this [button JSX](https://github.com/zesty-io/manager-ui/blob/master/src/apps/analytics/src/components/GoogleAuthOverlay/GoogleAuthOverlay.js#L85) currently exists in is a class component lets abstract that button into a functional component which can take advantage of the `usePermission` hook. The current `this.createAnalyticsPopup` click handler will need to be passed to this new component as a prop.

**Comment by ardeay** [comment]
Bump
