### ISSUE TITLE
Broken media button

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/manager-ui#893]
**Screenshots**
![media-selected-button](https://user-images.githubusercontent.com/208819/132590658-d175f3fe-7c61-45d5-b818-ad9a918184d6.png)

Also the red text on the default button appears to be a one off. We should try and get this aligned to the design-system but keep the experience of warning when you've reach the maximum image selection.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser firefox
 - Version latest

**Additional context**

**Comment by d88naimi** [comment]
The red is turned on in this image because they have already hit the limit of one. If the image options are more than one then red wont be lit up yet.

<img width="476" alt="Screen Shot 2021-09-08 at 4 13 30 PM" src="https://user-images.githubusercontent.com/22800749/132597700-163a26d6-81ef-4ce4-8a98-ff9df2afb3ef.png">
